# Generated by Django 3.2.4 on 2021-11-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='issued_quantity',
            new_name='issue_quantity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='received_quantity',
            new_name='receive_quantity',
        ),
    ]
