# Generated by Django 3.2.8 on 2021-10-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('product_name', models.CharField(max_length=20, null=True)),
                ('product_id', models.PositiveSmallIntegerField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('Date_ordered', models.DateField(null=True)),
                ('category', models.CharField(choices=[('1', 'vegetable'), ('2', 'dry goods'), ('3', 'others')], max_length=4, null=True)),
                ('Supplier_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Supplier_email', models.EmailField(max_length=30, null=True)),
            ],
        ),
    ]
